# Generated by Django 4.2 on 2025-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_category_post_notification_comment_bookmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
